# Generated by Django 5.0.3 on 2024-03-24 19:22

import paint_company_project.paint_inventory.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', paint_company_project.paint_inventory.utils.CustomBigHashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=13, prefix='pnt_', primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('grey', 'Grey'), ('black', 'Black'), ('white', 'White'), ('purple', 'Purple')], max_length=255, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('running_low', 'Running Low'), ('out_of_stock', 'Out of Stock')], max_length=255)),
                ('inventory', models.IntegerField(default=0)),
            ],
        ),
    ]
